//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricZat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feature
    {
        public int feature_id { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
        public byte[] ImageFile { get; set; }
        public int post_id { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
