//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricZat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CricZatEntities4 : DbContext
    {
        public CricZatEntities4()
            : base("name=CricZatEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<feature> features { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<userTable> userTables { get; set; }
    }
}
